ProjectEND/Controllers/DocController.cs
using ProjectEND.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectEND.Controllers
{
    public class DocController : Controller
    {
        private ProjectDEntities db = new ProjectDEntities();
        // GET: Doc
        public ActionResult Index()
        {
            return View(db.Dormitory);
        }
        // GET: Title/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Title/Create
        [HttpPost]
        public ActionResult Create(Dormitory cre)
        {
            try
            {
                db.Dormitory.Add(cre);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Title/Edit/5
        public ActionResult Edit(int id)
        {
            var ed = db.Dormitory.Find(id);
            return View(ed);
        }

        // POST: Title/Edit/5
        [HttpPost]
        public ActionResult Edit(Dormitory edit)
        {
            try
            {
                db.Entry(edit).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Title/Delete/5
        public ActionResult Delete(int id)
        {
            var del = db.Dormitory.Find(id);
            try
            {
                db.Dormitory.Remove(del);
                db.SaveChanges();
                TempData["Com"] = true;
                return RedirectToAction("Index");
            }
            catch
            {
                TempData["ChkDelete"] = true;
            }
            return RedirectToAction("Index");
        }
    }
}

ProjectEND/Views/Doc/Create.cshtml
@model ProjectEND.Models.Dormitory

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}

<form action="@Url.Action("Create","Doc")" method="post">
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>เพิ่มหอพัก</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Doc_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Doc_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Doc_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ตกลง" class="btn btn-primary" />
                <a class="btn btn-danger" href="@Url.Action("Index","Doc")">กลับ</a>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjectEND/Views/Doc/Edit.cshtml
@model ProjectEND.Models.Dormitory

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}



    <form action="@Url.Action("Edit","Doc")" method="post">
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Dormitory</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Doc_id)

            <div class="form-group">
                @Html.LabelFor(model => model.Doc_Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Doc_Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Doc_Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="ยืนยัน" class="btn btn-default" />
                </div>
            </div>
        </div>

    </form>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjectEND/Views/Doc/Index.cshtml
@model IEnumerable<ProjectEND.Models.Dormitory>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}
<link href="~/css/jquery.dataTables.css" rel="stylesheet" />
<h4>จัดการหอพัก</h4>
@if (TempData["ChkDelete"] != null)
{
    if ((bool)TempData["ChkDelete"])
    {
        <div class="alert alert-dismissible alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <h4 class="alert-heading">ERORR!</h4>
            <p class="mb-0">ไม่สามารถลบได้เนื่องจากมีการใช้งานข้อมูลนี้อยุ่</p>
        </div>

    }
}
@if (TempData["Com"] != null)
{
    if ((bool)TempData["Com"])
    {
        <div class="alert alert-dismissible alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <h4 class="alert-heading">Success!</h4>
            <p class="mb-0">ลบข้อมูลสำเร็จ</p>
        </div>
    }
}
<a style="margin-bottom:10px" class="btn btn-success" href="@Url.Action("Create","Doc")">เพิ่ม</a>
<table class="display" id="MyTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Doc_id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Doc_Name)
            </th>
            <th></th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tbody>
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Doc_id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Doc_Name)
                </td>
                <td>
                    <a class="btn btn-warning" href="@Url.Action("Edit","Doc",new { id=item.Doc_id})">แก้ไข</a>
                    <a class="btn btn-danger" onclick="Delete('@item.Doc_id')">ลบ</a>
                </td>
            </tr>
        </tbody>
    }

</table>
@section Scripts{
    <script src="~/Scripts/jquery.dataTables.js"></script>
    <script>
        $(document).ready(function () {
            $('#MyTable').DataTable();
        });
    </script>
}
<script>
    function Delete(id) {
        Swal.fire({
            title: 'ต้องการลบใช่หรือไม่?',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'ยืนยัน',
            cancelButtonText: 'ยกเลิก'
        }).then((result) => {
            if (result.isConfirmed) {
                 window.location.href = '@Url.Action("Delete","Doc")/' + id
            }
        })
    }
</script>