ProjectEND/Controllers/PaymentRoomController.cs
using ProjectEND.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectEND.Controllers
{
    public class PaymentRoomController : Controller
    {
        private ProjectDEntities db = new ProjectDEntities();
        // GET: PaymentRoom
        public ActionResult Index()
        {
            var data = db.Payment.ToList();
            return View(data);
        }
        public ActionResult Pay(int id)
        {
            ViewBag.StaPay_Id = new SelectList(db.StatusPayment,"StaPay_Id","StaPay_Name");
            Session["OrderID"] = id;
            return View();
        }
        [HttpPost]
        public ActionResult Pay(Payment payroom)
        {
            if (payroom.Upfile != null)
            {
                byte[] Temp = new byte[payroom.Upfile.ContentLength];
                payroom.Upfile.InputStream.Read(Temp, 0, payroom.Upfile.ContentLength);
                payroom.Payment_Pic = Temp; // เนื้อภาพ
            }
            var user = Session["USER"] as ProjectEND.Models.DataUser;
            var UD = db.DataUser.Find(user.User_id);
            UD.Sta_User_id = 4;

            try
            {
                var last = db.Payment.OrderByDescending(c => c.Payment_Id).FirstOrDefault();
                if (last == null)
                {
                    payroom.Payment_Id = 1;
                }
                else
                {
                    payroom.Payment_Id = last.Payment_Id + 1;
                }
                db.Payment.Add(payroom);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            catch (Exception)
            {
            }
            ViewBag.StaPay_Id = new SelectList(db.StatusPayment,"StaPay_Id","StaPay_Name");
            return View();
        }
        public ActionResult Confirm(int id)
        {
            var data = db.Payment.Find(id);
            data.Order.Sta_Id = 2;
            data.Order.DataUser.Sta_User_id = 3;
            data.Order.Room.StaRoom_ID = 2;
            db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public ActionResult Delete(int id)
        {
            var del = db.Payment.Find(id);
            try
            {
                db.Payment.Remove(del);
                db.SaveChanges();
                TempData["Com"] = true;
                return RedirectToAction(nameof(Index));
            }
            catch { TempData["ChkDelete"] = true; }
            return RedirectToAction(nameof(Index));


        }
        public ActionResult Detail(int id)
        {
            var de = db.Payment.Find(id);
            return View(de);
        }
    }
}

ProjectEND/Views/PaymentRoom/Detail.cshtml
@model ProjectEND.Models.Payment

@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}

<h2>Detail</h2>

<div>
    <h4>Payment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Payment_Id) :  @Html.DisplayFor(model => model.Payment_Id)
        </dt>
        <dt>
            @Html.DisplayNameFor(model => model.PaymentOrder_Id) :  @Html.DisplayFor(model => model.PaymentOrder_Id)
        </dt>
        <dt>
            @Html.DisplayNameFor(model => model.Order.DataUser.User_FristName)-@Html.DisplayNameFor(model => model.Order.DataUser.User_LastName) :
            @Html.DisplayFor(model => model.Order.DataUser.Title.Title_name) @Html.DisplayFor(model => model.Order.DataUser.User_FristName) @Html.DisplayFor(model => model.Order.DataUser.User_LastName)
        </dt>

        <dt>
            @Html.DisplayNameFor(model => model.Payment_Date) :  @Html.DisplayFor(model => model.Payment_Date)
        </dt>

        <dt>
            @Html.DisplayNameFor(model => model.Payment_Pic)

        </dt>

        <dd>
            @if (Model.Payment_Pic != null)
            {
                <img src="data:image/png;base64,@Convert.ToBase64String(Model.Payment_Pic)"
                     style="border-radius: 20px">
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Order.Date_In) : @Html.DisplayFor(model => model.Order.Date_In)
        </dt>

        <dt>
            @Html.DisplayNameFor(model => model.StatusPayment.StaPay_Name) :  @Html.DisplayFor(model => model.StatusPayment.StaPay_Name)
        </dt>
        <dt><a class="btn btn-danger" href="@Url.Action("Index","PaymentRoom")">กลับ</a></dt>
    </dl>
</div>

ProjectEND/Views/PaymentRoom/Index.cshtml
@model IEnumerable<ProjectEND.Models.Payment>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}

<h2>รายการชำระเงิน</h2>
<link href="~/css/jquery.dataTables.css" rel="stylesheet" />
@if (TempData["ChkDelete"] != null)
{
    if ((bool)TempData["ChkDelete"])
    {
        <div class="alert alert-dismissible alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <h4 class="alert-heading">ERORR!</h4>
            <p class="mb-0">ไม่สามารถลบได้เนื่องจากมีการใช้งานข้อมูลนี้อยุ่</p>
        </div>
    }
}
@if (TempData["Com"] != null)
{
    if ((bool)TempData["Com"])
    {
        <div class="alert alert-dismissible alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <h4 class="alert-heading">Success!</h4>
            <p class="mb-0">ลบข้อมูลสำเร็จ</p>
        </div>
    }
}
<table class="display" id="MyTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Payment_Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Payment_Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Payment_Pic)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PaymentOrder_Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StatusPayment.StaPay_Name)
            </th>
            <th></th>
        </tr>
    </thead>

    @foreach (var item in Model)
    {
        <tbody>
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Payment_Id)
                </td>
                <td>
                    @item.Payment_Date.Value.ToShortDateString()
                </td>
                <td>
                    @if (item.Payment_Pic != null)
                    {
                        <img src="data:image/png;base64,@Convert.ToBase64String(item.Payment_Pic)"
                             width="100" height="100" style="border-radius: 20px">
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PaymentOrder_Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StatusPayment.StaPay_Name)
                </td>
                <td>
                    <a class="btn btn-primary" href="@Url.Action("Detail","PaymentRoom",new {id=item.Payment_Id })">รายละเอียด</a>
                    @if (item.Order.Sta_Id == 1)
                    {
                        <a class="btn btn-success" href="@Url.Action("Confirm","PaymentRoom",new {id=item.Payment_Id })">ยืนยันการชำระ</a>
                    }
                    <a class="btn btn-danger" onclick="Delete('@item.Payment_Id')">ลบ</a>
                </td>
            </tr>
        </tbody>
    }
</table>
@section Scripts{
    <script src="~/Scripts/jquery.dataTables.js"></script>
    <script>
        $(document).ready(function () {
            $('#MyTable').DataTable();
        });
    </script>
}
<script>

    function Delete(id) {
        Swal.fire({
            title: 'ต้องการลบใช่หรือไม่?',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'ยืนยัน',
            cancelButtonText: 'ยกเลิก'
        }).then((result) => {
            if (result.isConfirmed) {

                window.location.href = '@Url.Action("Delete", "PaymentRoom")/' + id
            }
        })
    }
</script>

ProjectEND/Views/PaymentRoom/Pay.cshtml
@model ProjectEND.Models.Payment

@{
    ViewBag.Title = "Pay";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var user = Session["USER"] as ProjectEND.Models.DataUser;
    var star = Session["sta"];
}


<form action="@Url.Action("Pay", "PaymentRoom")" method="post" enctype="multipart/form-data">

    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ชำระเงิน</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PaymentOrder_Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaymentOrder_Id, new { htmlAttributes = new { @Value = Session["OrderID"], @class = "form-control", @readonly = "true" } })
                @Html.ValidationMessageFor(model => model.PaymentOrder_Id, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Order.DataUser.User_FristName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <p class="form-control">@user.User_FristName</p>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Order.DataUser.User_LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <a class="form-control">@user.User_LastName</a>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Payment_Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Payment_Date, new { htmlAttributes = new { @Value = DateTime.Now.ToString("yyyy/MM/dd"), @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.Payment_Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StaPay_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StaPay_Id", null, "---เลือกการชำระเงิน---", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StaPay_ID, "", new { @class = "text-danger" })
            </div>
        </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Payment_Pic, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Upfile, new { htmlAttributes = new { @class = "form-control" }, type = "file" })
                    @Html.ValidationMessageFor(model => model.Payment_Pic, "", new { @class = "text-danger" })
                </div>
            </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ตกลง" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}